apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
      - name: movie-app
        image: movie-booking-app:latest
        imagePullPolicy: Never   # ðŸ”¥ Add this
        ports:
        - containerPort: 80
